export const SET_LAYOUT = 'SET_LAYOUT'
export const SET_PROFILE = 'SET_PROFILE'
export const SET_TOKEN = 'SET_TOKEN'
export const LOG_OUT = 'LOG_OUT'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
