import './axios'
import './flatpickr'
import './vuelidate'
import './moment'
import './bootstrap-vue'
import './vue-lazyload'
import './vue-progressbar'

import '@/assets/libs/selectize/dist/css/selectize.css'
import '@/assets/css/tabler-buttons.min.css'
import '@/assets/css/tabler.min.css'
import '@/assets/libs/jquery/dist/jquery.slim.min'
import '@/assets/libs/bootstrap/dist/js/bootstrap.bundle.min'
import '@/assets/js/tabler.min'
